### PR TITLE
Allow building with Gradle

### PR DESCRIPTION
**Pull request by jskov-jyskebank-dk**
Only tested with linux host build for now.

### CODE REVIEW

**Comment by jskov-jyskebank-dk** [comment]
Hi @FDelporte 

Not sure if you want Gradle support, but I had to make it as a stepping stone for testing something anyway.

I am going to test Windows native builds, but prefer to use gradle.

Anyway, I see the build is failing. Interesting - did not touch any of the existing files (I should think).

Cheers,
Jesper

**Comment by FDelporte** [comment]
Thanks a lot Jesper! I'm personnaly a Maven-user, but indeed adding Gradle support as example for other users is great!

No clue yet why builds seem to be broken as indeed they should not be influenced by your commit. Will merge and check later what is happening.

**Comment by FDelporte** [comment]
FYI @jskovjyskebankdk builds are fixed!

**Comment by jskov-jyskebank-dk** [comment]
nice

**Pull request merged**
